### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by alecmarcus** [Upstatement/ups-public-library#20]
- [x] Update netflify deploy commands
- [x] Favicon
- [x] Site meta & manifest data
- [x] Ensure pages have proper titles
- [x] Double check package info
